#DB
PORT="5432"
REGION="us-east-1"
DBNAME="financial_facts_db"
DB_USERNAME_KEY="USERNAME_KEY"
DB_PASSWORD_KEY="PASSWORD_KEY"
DB_ENDPOINT_KEY="ENDPOINT_KEY"
S3_KEY="S3_KEY"
S3_SECRET_KEY="S3_SECRET_KEY"
BUCKET_NAME_KEY="BUCKET_NAME_KEY"

# Misc
USER_AGENT_VALUE_KEY = 'USER_AGENT_VALUE_KEY'
EMPTY = ''

# Urls
EDGAR_URL = "https://www.sec.gov/Archives/edgar"
DATA_ZIP_PATH = "/daily-index/xbrl/companyfacts.zip"
